
server:
    port: ${SERVER-PORT}

spring:
    application:
        name: config-service
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/TheLibraryGroup/config-files.git
        discovery:
            enabled: true
    security:
        user:
            name: confUser
            password: confPassword
            roles: SYSTEM

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA-CLIENT-SERVICEURL-DEFAULTZONE}
