spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/TheLibraryGroup/config-files.git
    security:
        user:
            name: confUser
            password: confPassword
            roles: SYSTEM
server:
    port: 8888
#eureka:
#    client:
#        serviceUrl:
#            defaultZone: http://discUser:discPassword@localhost:8761/eureka/
