
server:
    port: ${SERVER_PORT}

spring:
    application:
        name: configuration
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/TheLibraryGroup/config-files.git
        discovery:
            enabled: true
    security:
        user:
            name: confUser
            password: confPassword
            roles: SYSTEM
#    boot:
#        admin:
#            client:
#                instance:
#                    metadata:
#                        tags:
#                            environment: test
#                enabled: true
##                url: http://adminUser:adminPassword@localhost:8070
#                url: http://adminUser:adminPassword@localhost:8070

eureka:
    instance:
        leaseRenewalIntervalInSeconds: 10
        leaseExpirationDurationInSeconds: 2
        health-check-url-path: /actuator/health
        metadata-map:
            startup: ${random.int}    #needed to trigger info and endpoint update after restart
    client:
        registryFetchIntervalSeconds: 5
        serviceUrl:
            defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
        healthcheck:
            enabled: true

management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: "*"
